# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Trendology(object):
    def setupUi(self, Trendology):
        Trendology.setObjectName("Trendology")
        Trendology.resize(1024, 768)
        Trendology.setMinimumSize(QtCore.QSize(1024, 768))
        self.centralwidget = QtWidgets.QWidget(Trendology)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.listViewWells = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listViewWells.sizePolicy().hasHeightForWidth())
        self.listViewWells.setSizePolicy(sizePolicy)
        self.listViewWells.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listViewWells.setBaseSize(QtCore.QSize(300, 0))
        self.listViewWells.setMouseTracking(False)
        self.listViewWells.setTabKeyNavigation(False)
        self.listViewWells.setObjectName("listViewWells")
        self.verticalLayout.addWidget(self.listViewWells)
        self.labelWellData = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelWellData.setFont(font)
        self.labelWellData.setObjectName("labelWellData")
        self.verticalLayout.addWidget(self.labelWellData)
        self.listViewFormations = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listViewFormations.sizePolicy().hasHeightForWidth())
        self.listViewFormations.setSizePolicy(sizePolicy)
        self.listViewFormations.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listViewFormations.setBaseSize(QtCore.QSize(300, 0))
        self.listViewFormations.setMouseTracking(False)
        self.listViewFormations.setObjectName("listViewFormations")
        self.verticalLayout.addWidget(self.listViewFormations)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background: rgb(240, 240, 240)")
        self.tabWidget.setObjectName("tabWidget")
        self.tabSelData = QtWidgets.QWidget()
        self.tabSelData.setObjectName("tabSelData")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabSelData)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tabSelData)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setStyleSheet("background: white")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tabSelData, "")
        self.tabHist = QtWidgets.QWidget()
        self.tabHist.setObjectName("tabHist")
        self.tabWidget.addTab(self.tabHist, "")
        self.tabDist = QtWidgets.QWidget()
        self.tabDist.setObjectName("tabDist")
        self.tabWidget.addTab(self.tabDist, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        Trendology.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Trendology)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuSettings.sizePolicy().hasHeightForWidth())
        self.menuSettings.setSizePolicy(sizePolicy)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Trendology.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Trendology)
        self.statusbar.setObjectName("statusbar")
        Trendology.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(Trendology)
        self.actionExit.setObjectName("actionExit")
        self.actionLoad_File = QtWidgets.QAction(Trendology)
        self.actionLoad_File.setObjectName("actionLoad_File")
        self.actionSave_Project = QtWidgets.QAction(Trendology)
        self.actionSave_Project.setObjectName("actionSave_Project")
        self.menuFile.addAction(self.actionLoad_File)
        self.menuFile.addAction(self.actionSave_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Trendology)
        self.tabWidget.setCurrentIndex(0)
        self.actionExit.triggered.connect(Trendology.close)
        QtCore.QMetaObject.connectSlotsByName(Trendology)

    def retranslateUi(self, Trendology):
        _translate = QtCore.QCoreApplication.translate
        Trendology.setWindowTitle(_translate("Trendology", "MainWindow"))
        self.label_2.setText(_translate("Trendology", "Well Data"))
        self.labelWellData.setText(_translate("Trendology", "Formations"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSelData), _translate("Trendology", "Selected Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHist), _translate("Trendology", "Histogram"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDist), _translate("Trendology", "Distribution"))
        self.menuFile.setTitle(_translate("Trendology", "File"))
        self.menuEdit.setTitle(_translate("Trendology", "Edit"))
        self.menuView.setTitle(_translate("Trendology", "View"))
        self.menuSettings.setTitle(_translate("Trendology", "Settings"))
        self.menuHelp.setTitle(_translate("Trendology", "Help"))
        self.actionExit.setText(_translate("Trendology", "Exit"))
        self.actionLoad_File.setText(_translate("Trendology", "Load File"))
        self.actionSave_Project.setText(_translate("Trendology", "Save Project"))

